### PR TITLE
Add read_only option to samba_share

### PR DESCRIPTION
**Pull request by whatcould**
Just like it says in the title...

### CODE REVIEW

**Comment by damacus** [comment]
@whatcould thanks! 

Is there any *good* way of testing this at all?

**Comment by rshade** [comment]
create one try and touch a file maybe

**Comment by damacus** [comment]
Sorry this slipped through the work schedule. I'll get this released now thanks @whatcould

**Comment by whatcould** [comment]
Thanks... I missed the test question. I didn't see any tests for whether these options were being passed correctly, short of just testing whether they appeared in the smb.conf. It's a pretty straightforward change anyhow.

**Pull request merged**
